### ISSUE TITLE
Forge - Fluid Output Broken

### ISSUE THREAD

**Issue by enigmaquip** [KubeJS-Mods/KubeJS-Create#13]
It appears that recipes with fluid outputs are not deserialized/serialized properly

Error parsing recipe create:mixing/tea[create:mixing]: {"type":"create:mixing","ingredients":[{"tag":"minecraft:leaves"},{"fluid":"minecraft:water","nbt":{},"amount":250},{"fluidTag":"forge:milk","amount":250}],"results":[{"fluid":"create:tea"}],"heatRequirement":"heated"}: com.google.gson.JsonSyntaxException: Missing amount, expected to find a Int

Error parsing recipe create:emptying/builders_tea[create:emptying]: {"type":"create:emptying","ingredients":[{"item":"create:builders_tea"}],"results":[{"item":"minecraft:glass_bottle","count":1},{"fluid":"create:tea"}]}: com.google.gson.JsonSyntaxException: Missing amount, expected to find a Int

Server Export has this with KubeJS Create
```json
        "create:emptying/builders_tea": {
            "recipe": {
                "type": "create:emptying",
                "ingredients": [
                    {"item": "create:builders_tea"}
                ],
                "results": [
                    {"item": "minecraft:glass_bottle", "count": 1},
                    {"fluid": "create:tea"}
                ]
            }
        }
```
and this without
```json
        "create:emptying/builders_tea": {
            "recipe": {
                "type": "create:emptying",
                "ingredients": [
                    {"item": "create:builders_tea"}
                ],
                "results": [
                    {"item": "minecraft:glass_bottle"},
                    {"fluid": "create:tea", "amount": 250}
                ]
            }
        }
```

**Comment by enigmaquip** [comment]
https://github.com/KubeJS-Mods/KubeJS-Create/blob/1.18/main/common/src/main/java/dev/latvian/mods/kubejs/create/ProcessingRecipeJS.java#L58
```
if (resultJson.has("fluid")) {
	outputFluids.add(FluidStackJS.fromJson(resultJson.get("fluid")));
```
should this line just be passing resultJson to FluidStackJS?

**Comment by MaxNeedsSnacks** [comment]
You're absolutely right about that, I must've messed that up somehow :/ Give me a bit to fix this

**Comment by enigmaquip** [comment]
Thanks!
