### ISSUE TITLE
Cant add custom recipe on create fabric(crushing or any other create recipe)

### ISSUE THREAD

**Issue by SercraftGaming** [KubeJS-Mods/KubeJS-Create#22]
### Minecraft Version

1.18.2

### KubeJS Version

1802.5.5

### Rhino Version

1202.2.0

### Architectury Version

4.9.83

### Forge/Fabric Version

Fabric 0.14.9

### Describe your issue

Failed to create recipe for type 'create:mechanical_crafting': Custom recipe has to use a single json object argument!

settings.logAddedRecipes = true
settings.logRemovedRecipes = true
settings.logSkippedRecipes = false
settings.logErroringRecipes = true

onEvent('recipes', event => {
event.recipes.createMechanicalCrafting('minecraft:piston', [
  'CCCCC',
  'CPIPC',
  'CPRPC'
], {
  C: '#forge:cobblestone',
  P: '#minecraft:planks',
  R: '#forge:dusts/redstone',
  I: '#forge:ingots/iron'
})
})

**Comment by SercraftGaming** [comment]
Sorry, here it is
[latest.log](https://github.com/KubeJS-Mods/KubeJS-Create/files/9489410/latest.log)

**Comment by MaxNeedsSnacks** [comment]
Yeah, KubeJS create isn’t even in that mod list, so you probably downloaded
the Forge version of the mod if anything, can you try and verify that real
quick?

**Comment by SercraftGaming** [comment]
I have kubejs mod but didnt have kubjs create mod, do i need to install it?

**Comment by MaxNeedsSnacks** [comment]
If you want to use the easier syntax for Create recipes, yes ^^

**Comment by SercraftGaming** [comment]
Oh, sorry

**Comment by SercraftGaming** [comment]
where i can download it?

**Comment by MaxNeedsSnacks** [comment]
That would be https://www.curseforge.com/minecraft/mc-mods/kubejs-create on CurseForge

**Comment by SercraftGaming** [comment]
I did not see what it is on 1.18.2, lol

**Comment by SercraftGaming** [comment]
Thanks (:
