### ISSUE TITLE
1.19+

### ISSUE THREAD

**Issue by DJ-Laser** [KubeJS-Mods/KubeJS-Create#25]
Can I use this for 1.19.2 or will it not work? I want to make custom sequenced assembly for my modpack.

**Comment by AaronSpinner** [comment]
I'm struggeling with updating my modpack to 1.19 since i cant use the custom crafting recepies for create, it would mean a lot for me if this mod gets updatet to 1.19.2 :)

**Comment by JakeNumber69** [comment]
please do it

**Comment by JakeNumber69** [comment]
PLEAAAAAASE

**Comment by JakeNumber69** [comment]
I SPENT A WHOLE 10 DAYS TRYING TO DO MECHANICAL CRAFTING FOR MY MODPACK WITHOUT THIS

**Comment by MichaelHillcox** [comment]
It'll be updated when it's updated. Locking due to spam

**Comment by MaxNeedsSnacks** [comment]
The KubeJS addons will be updated whenever we manage to release a stable version of the mod for 1.19. As we currently have multiple issues to deal with still and don't feel confident releasing a stable version for 1.19.2 so close to a new, even more breaking update from Mojang's end (1.19.3) dropping, that'll take a while...
