### ISSUE TITLE
[1.19.2] Latest create causes crash on startup

### ISSUE THREAD

**Issue by DelviousCrafts** [KubeJS-Mods/KubeJS-Create#29]
Create recently updated causing a crash on startup with KubeJS Create installed

(crash report)[https://gist.github.com/DelviousCrafts/35c601115146ed1a1d5f7fa40973d027]

Versions:
- Minecraft: 1.19.2
- Forge: 43.2.11
- Create: 0.5.1.a
- KubeJS: 6.0-build.142
- KubeJS Create: 1902.1.1-build.35
- Rhino: 1902.2.2-build.268
- Architectury: 6.5.82

**Comment by keeptpa** [comment]
Create 0.5.1 had move class SequencedAssemblyItem to here:

```java
src/main/java/com/simibubi/create/content/processing/sequenced/SequencedAssemblyItem.java
``` 

so [this ](https://github.com/KubeJS-Mods/KubeJS-Create/blob/80bc940e2479adde9b976ecf8d4caee02388e34e/common/src/main/java/dev/latvian/mods/kubejs/create/SequencedAssemblyItemBuilder.java#L3)will throw a error now as it cannot find this class anymore

I forked this, tried to fix it, but fail on compile testing on git action.
It seems a jei relatived something couldn't be reach.

Oh, the create [version](https://github.com/KubeJS-Mods/KubeJS-Create/blob/80bc940e2479adde9b976ecf8d4caee02388e34e/gradle.properties#L15) in gradle is also need to be modified. I did but gradle said it couldn't be found too. No idea if it's not uploaded to pom yet.

**Comment by MaxNeedsSnacks** [comment]
I would use this to "complain" about breaking changes in minor versions, but we're about to do the same with KubeJS itself so LMAO

We're on it though, might be a little bit before then tho

**Comment by MrFastZombie** [comment]
You probably already know, but I just want to make sure: It also affects 1.18.2.
