### ISSUE TITLE
Incompatable with Create 0.3.2

### ISSUE THREAD

**Issue by TrpgOne** [KubeJS-Mods/KubeJS-Create#3]
Crashes with Create 0.3.2 beacuse the Handheld Blockzapper was removed.

**Comment by Unixkitty** [comment]
Probably unnecessary, but here's a crash log just in case. 
[crash-2021-07-13_00.26.42-client.txt](https://github.com/KubeJS-Mods/KubeJS-Create/files/6823119/crash-2021-07-13_00.26.42-client.txt)
