### ISSUE TITLE
Fabric - Fluid amount is bugged [SOLVED]

### ISSUE THREAD

**Issue by MaDo15** [KubeJS-Mods/KubeJS-Create#30]
When I wanted to create this recipe, the Fluid amount was not 250 mb.
```
    event.recipes.createMixing('minecraft:coal', [
        'kubejs:raw_coal',
        Fluid.of('water',250)
      ])
```

![2023-05-24_18 11 56](https://github.com/KubeJS-Mods/KubeJS-Create/assets/119709328/b87ee8d4-42b6-4f0b-a498-a018b9a9c474)

**Comment by MaxNeedsSnacks** [comment]
Not really an issue; Fabric uses 81000 for bucket amounts by default, so you'll have to multiply your values by 81. This should still be documented better, though, or we should add a constant MILLIBUCKET / BUCKET / whatever to KubeJS itself

**Comment by MaDo15** [comment]
Ah, thanks. Yeah in forge it is different.

> Not really an issue; Fabric uses 81000 for bucket amounts by default, so you'll have to multiply your values by 81. This should still be documented better, though, or we should add a constant MILLIBUCKET / BUCKET / whatever to KubeJS itself
