### ISSUE TITLE
Milling recipes don't complete

### ISSUE THREAD

**Issue by ChiefArug** [KubeJS-Mods/KubeJS-Create#32]
Using rhino-forge-1902.2.2-build.268, kubejs-forge-1902.6.1-build.9999 (build.236 with https://github.com/KubeJS-Mods/KubeJS/pull/646 applied), kubejs-create-forge-1902.2.4-build.11, architectury-6.5.85-forge and forge 43.2.14

Using this code 
```js
event.recipes.create.milling("cobblestone", "kubejs:layer_1")
```
the recipe shows up in jei, and the item is accepted into the millstone, but it doesnt ever complete and produce an output. Some particles do show, but not as many as other recipes.
Using this code with `event.custom` does work, the recipe shows up in jei and 
```js
  event.custom({
    "type": "create:milling",
    "ingredients": [
      {
        "item": "kubejs:layer_1"
      }
    ],
    "processingTime": 200,
    "results": [
      {
        "item": "minecraft:cobblestone"
      }
    ]
  })
```

**Comment by ChiefArug** [comment]
It seems it caches the last recipe too, so to test it accurately you need to mill another default recipe after each /reload to clear the cache.

**Comment by oierbravo** [comment]
Try adding `.processingTime(200)`

**Comment by MaxNeedsSnacks** [comment]
Fixed by implementing a default value that is always written for required recipe types (#35)
